Adding label research page
openui/open-ui pull request #348
Opened 2021-05-20 17:28 UTC by sopranopillow

Add research page for the `Label` component.

2021-05-23 17:32 UTC, gregwhitworth requested changes

2021-05-23 17:32 UTC, gregwhitworth commented on research/src/pages/label.research.mdx
> +menu: Analysis
A PR that landed just before yours modified this to 'Research' so please update

2022-03-22 08:05 UTC, andrico1234 commented
Hi @sopranopillow , just bumping this PR. are you happy for a re-review?

2022-03-22 17:13 UTC, sopranopillow commented
> Hi @sopranopillow , just bumping this PR. are you happy for a re-review?

For sure!

2023-03-11 02:08 UTC, gregwhitworth commented
Closing this due to the lack of activity, it can always be re-opened in the future.

2023-03-11 02:08 UTC, closed without merging