chore: update kolibri urls
openui/open-ui pull request #680
Opened 2023-03-14 03:14 UTC by deleonio

We have a new documentation site with seo urls.

2023-03-15 03:17 UTC, deleonio commented
Please rerun the IPR-Check. Thank you.

2023-03-16 21:31 UTC, andrico1234 commented on site/src/pages/components/table.mdx
> +| KoliBri     | [Table](https://public-ui.github.io/docs/components/table)                                                                                            | [Playground](https://codesandbo
it looks like you KoliBri is sandwiched between the Evergreen table link and playground

2023-03-16 21:33 UTC, andrico1234 commented on site/src/pages/components/table.mdx
> +| KoliBri     | [Table](https://public-ui.github.io/docs/components/table)                                                                                            | [Playground](https://codesandbo
```suggestion
| KoliBri     | [Table](https://public-ui.github.io/docs/components/table)                                                                                            | -                     | `<div>`                       | -                                                                |
```

2023-03-16 21:37 UTC, andrico1234 requested changes
Thanks for making the change, I have just one requested change and then I'm happy for this to be merged in

2023-03-18 10:42 UTC, deleonio commented
@andrico1234 really cool, thank you.

2023-03-18 16:05 UTC, andrico1234 approved these changes

2023-03-18 16:05 UTC, andrico1234 commented
Thanks for this! :)

2023-03-18 16:05 UTC, merged